### ISSUE TITLE
Space efficiency.

### ISSUE THREAD

**Issue by wyattbenno777** [personaelabs/shockwave-plus#1]
I am not sure where to ask this.. so I will do it here.
One cool thing about client side proving with Nova and other 'folding' scheme is the space efficiency aspect.
Very small 30mb~ when compared against many FRI based systems.

Will Shockwave+ make phones and computers buzz and become hot?
The main benefit is getting rid of the need of Cycles of curves allowing for 'native-field' arithmetic?

I think the goals/process of your work are amazing!

Thank you.

**Comment by DanTehrani** [comment]
Agree!
> One cool thing about client-side proving with Nova and other folding schemes is the space efficiency aspect.

Shockwave+ doesn't include a folding scheme but can provide space efficiency through native-field arithmetic. Circuits written in native field are a lot smaller than circuits in the non-native field (because non-native circuits require bigint operations which are expensive i.e. leads to a lot of constraints).

**Comment by DanTehrani** [comment]
I created a channel for Shockwave+ discussions in our discord https://discord.gg/WpsvHDxJ
so feel free to post questions there!
